spring:
  datasource:
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            - endpoint: https://practice-spring-boot.vault.azure.net/

logging:
  level:
    com.azure.spring: DEBUG
    com.azure.security.keyvault: DEBUG
    com.azure.identity: DEBUG

jwt:
  secret: ${DB-JWT-SECRET}
  expiration: 86400000
